modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jujutsucraftaddon"
version="6.1"
displayName="JJKUR"
displayURL="https://www.curseforge.com/members/satuxhi/projects"
logoFile="logo.png"
credits="Made By Satushi"
authors="Satushi"
description="Reworked Addon, Jujutsu Kaisen: Ultimate"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.jujutsucraftaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jujutsucraftaddon]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jujutsucraftaddon]]
    modId="jujutsucraft"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jujutsucraftaddon]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jujutsucraftaddon]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration