
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jujutsucraftaddon.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.effect.MobEffect;

import net.mcreator.jujutsucraftaddon.potion.WorldSlashEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.VowFriendMobEffect;
import net.mcreator.jujutsucraftaddon.potion.TrainingMobEffect;
import net.mcreator.jujutsucraftaddon.potion.TojiEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.TestingMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SukunaPowersMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SukunaMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SoroiroMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SokaMonaMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SizeMobEffect;
import net.mcreator.jujutsucraftaddon.potion.SimpleDomainMaxMobEffect;
import net.mcreator.jujutsucraftaddon.potion.ShrineEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.RidingEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.RedEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.RampageZoneMobEffect;
import net.mcreator.jujutsucraftaddon.potion.RCTCutMobEffect;
import net.mcreator.jujutsucraftaddon.potion.OvertimeMobEffect;
import net.mcreator.jujutsucraftaddon.potion.OneHundredAndTwentyMobEffect;
import net.mcreator.jujutsucraftaddon.potion.MurasakiEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.MeditationStateMobEffect;
import net.mcreator.jujutsucraftaddon.potion.ManifestationMobEffect;
import net.mcreator.jujutsucraftaddon.potion.LimbsEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.KokusenEffectTwoMobEffect;
import net.mcreator.jujutsucraftaddon.potion.KokusenEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.JogoFlameMobEffect;
import net.mcreator.jujutsucraftaddon.potion.JackpotMobEffect;
import net.mcreator.jujutsucraftaddon.potion.ItadoriRampageMobEffect;
import net.mcreator.jujutsucraftaddon.potion.ItadoriAwakeningMobEffect;
import net.mcreator.jujutsucraftaddon.potion.InfinityMobEffect;
import net.mcreator.jujutsucraftaddon.potion.HourCinderellaMobEffect;
import net.mcreator.jujutsucraftaddon.potion.HidingMobEffect;
import net.mcreator.jujutsucraftaddon.potion.HeianMobEffect;
import net.mcreator.jujutsucraftaddon.potion.HWBMobEffect;
import net.mcreator.jujutsucraftaddon.potion.GojoRampageMobEffect;
import net.mcreator.jujutsucraftaddon.potion.GojoImbuedPowerMobEffect;
import net.mcreator.jujutsucraftaddon.potion.GojoBlueAnimMobEffect;
import net.mcreator.jujutsucraftaddon.potion.GojoAwakeningMobEffect;
import net.mcreator.jujutsucraftaddon.potion.FutureSightEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DomainTimeMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DomainEffectStartMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DomainEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DomainBreakMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DashMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DashCooldownMobEffect;
import net.mcreator.jujutsucraftaddon.potion.DagonMobEffect;
import net.mcreator.jujutsucraftaddon.potion.CounterMobEffect;
import net.mcreator.jujutsucraftaddon.potion.CounterCDMobEffect;
import net.mcreator.jujutsucraftaddon.potion.CooldownTojiMobEffect;
import net.mcreator.jujutsucraftaddon.potion.CooldownItadoriMobEffect;
import net.mcreator.jujutsucraftaddon.potion.CdTAKABA2MobEffect;
import net.mcreator.jujutsucraftaddon.potion.CDtakabaMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BrokenBrainMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BlueEffectMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BlackHoleMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BlackFlashCutMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BindingVowMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BindingVowCooldownMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BerserkMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BasePotionMobEffect;
import net.mcreator.jujutsucraftaddon.potion.BarrierlessCooldownMobEffect;
import net.mcreator.jujutsucraftaddon.potion.AwakeningMobEffect;
import net.mcreator.jujutsucraftaddon.potion.AntiHealMobEffect;
import net.mcreator.jujutsucraftaddon.potion.AnimationTwoMobEffect;
import net.mcreator.jujutsucraftaddon.potion.AnimationOneMobEffect;
import net.mcreator.jujutsucraftaddon.potion.AnimMobEffect;
import net.mcreator.jujutsucraftaddon.potion.Anim4MobEffect;
import net.mcreator.jujutsucraftaddon.potion.Anim3MobEffect;
import net.mcreator.jujutsucraftaddon.potion.Anim2MobEffect;
import net.mcreator.jujutsucraftaddon.potion.Anim1MobEffect;
import net.mcreator.jujutsucraftaddon.JujutsucraftaddonMod;

public class JujutsucraftaddonModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, JujutsucraftaddonMod.MODID);
	public static final RegistryObject<MobEffect> FUTURE_SIGHT_EFFECT = REGISTRY.register("future_sight_effect", () -> new FutureSightEffectMobEffect());
	public static final RegistryObject<MobEffect> AWAKENING = REGISTRY.register("awakening", () -> new AwakeningMobEffect());
	public static final RegistryObject<MobEffect> MURASAKI_EFFECT = REGISTRY.register("murasaki_effect", () -> new MurasakiEffectMobEffect());
	public static final RegistryObject<MobEffect> DOMAIN_EFFECT = REGISTRY.register("domain_effect", () -> new DomainEffectMobEffect());
	public static final RegistryObject<MobEffect> DASH = REGISTRY.register("dash", () -> new DashMobEffect());
	public static final RegistryObject<MobEffect> DASH_COOLDOWN = REGISTRY.register("dash_cooldown", () -> new DashCooldownMobEffect());
	public static final RegistryObject<MobEffect> RED_EFFECT = REGISTRY.register("red_effect", () -> new RedEffectMobEffect());
	public static final RegistryObject<MobEffect> SIMPLE_DOMAIN_MAX = REGISTRY.register("simple_domain_max", () -> new SimpleDomainMaxMobEffect());
	public static final RegistryObject<MobEffect> SIZE = REGISTRY.register("size", () -> new SizeMobEffect());
	public static final RegistryObject<MobEffect> BROKEN_BRAIN = REGISTRY.register("broken_brain", () -> new BrokenBrainMobEffect());
	public static final RegistryObject<MobEffect> RAMPAGE_ZONE = REGISTRY.register("rampage_zone", () -> new RampageZoneMobEffect());
	public static final RegistryObject<MobEffect> JACKPOT = REGISTRY.register("jackpot", () -> new JackpotMobEffect());
	public static final RegistryObject<MobEffect> BARRIERLESS_COOLDOWN = REGISTRY.register("barrierless_cooldown", () -> new BarrierlessCooldownMobEffect());
	public static final RegistryObject<MobEffect> BINDING_VOW = REGISTRY.register("binding_vow", () -> new BindingVowMobEffect());
	public static final RegistryObject<MobEffect> BINDING_VOW_COOLDOWN = REGISTRY.register("binding_vow_cooldown", () -> new BindingVowCooldownMobEffect());
	public static final RegistryObject<MobEffect> OVERTIME = REGISTRY.register("overtime", () -> new OvertimeMobEffect());
	public static final RegistryObject<MobEffect> GOJO_RAMPAGE = REGISTRY.register("gojo_rampage", () -> new GojoRampageMobEffect());
	public static final RegistryObject<MobEffect> DAGON = REGISTRY.register("dagon", () -> new DagonMobEffect());
	public static final RegistryObject<MobEffect> ITADORI_RAMPAGE = REGISTRY.register("itadori_rampage", () -> new ItadoriRampageMobEffect());
	public static final RegistryObject<MobEffect> ANIMATION_ONE = REGISTRY.register("animation_one", () -> new AnimationOneMobEffect());
	public static final RegistryObject<MobEffect> ANIMATION_TWO = REGISTRY.register("animation_two", () -> new AnimationTwoMobEffect());
	public static final RegistryObject<MobEffect> DOMAIN_EFFECT_START = REGISTRY.register("domain_effect_start", () -> new DomainEffectStartMobEffect());
	public static final RegistryObject<MobEffect> COUNTER = REGISTRY.register("counter", () -> new CounterMobEffect());
	public static final RegistryObject<MobEffect> COUNTER_CD = REGISTRY.register("counter_cd", () -> new CounterCDMobEffect());
	public static final RegistryObject<MobEffect> GOJO_IMBUED_POWER = REGISTRY.register("gojo_imbued_power", () -> new GojoImbuedPowerMobEffect());
	public static final RegistryObject<MobEffect> SUKUNA_POWERS = REGISTRY.register("sukuna_powers", () -> new SukunaPowersMobEffect());
	public static final RegistryObject<MobEffect> TOJI_EFFECT = REGISTRY.register("toji_effect", () -> new TojiEffectMobEffect());
	public static final RegistryObject<MobEffect> SHRINE_EFFECT = REGISTRY.register("shrine_effect", () -> new ShrineEffectMobEffect());
	public static final RegistryObject<MobEffect> BLUE_EFFECT = REGISTRY.register("blue_effect", () -> new BlueEffectMobEffect());
	public static final RegistryObject<MobEffect> KOKUSEN_EFFECT = REGISTRY.register("kokusen_effect", () -> new KokusenEffectMobEffect());
	public static final RegistryObject<MobEffect> KOKUSEN_EFFECT_TWO = REGISTRY.register("kokusen_effect_two", () -> new KokusenEffectTwoMobEffect());
	public static final RegistryObject<MobEffect> LIMBS_EFFECT = REGISTRY.register("limbs_effect", () -> new LimbsEffectMobEffect());
	public static final RegistryObject<MobEffect> RIDING_EFFECT = REGISTRY.register("riding_effect", () -> new RidingEffectMobEffect());
	public static final RegistryObject<MobEffect> WORLD_SLASH_EFFECT = REGISTRY.register("world_slash_effect", () -> new WorldSlashEffectMobEffect());
	public static final RegistryObject<MobEffect> ITADORI_AWAKENING = REGISTRY.register("itadori_awakening", () -> new ItadoriAwakeningMobEffect());
	public static final RegistryObject<MobEffect> SUKUNA = REGISTRY.register("sukuna", () -> new SukunaMobEffect());
	public static final RegistryObject<MobEffect> DOMAIN_BREAK = REGISTRY.register("domain_break", () -> new DomainBreakMobEffect());
	public static final RegistryObject<MobEffect> GOJO_BLUE_ANIM = REGISTRY.register("gojo_blue_anim", () -> new GojoBlueAnimMobEffect());
	public static final RegistryObject<MobEffect> HWB = REGISTRY.register("hwb", () -> new HWBMobEffect());
	public static final RegistryObject<MobEffect> BASE_POTION = REGISTRY.register("base_potion", () -> new BasePotionMobEffect());
	public static final RegistryObject<MobEffect> BLACK_HOLE = REGISTRY.register("black_hole", () -> new BlackHoleMobEffect());
	public static final RegistryObject<MobEffect> C_DTAKABA = REGISTRY.register("c_dtakaba", () -> new CDtakabaMobEffect());
	public static final RegistryObject<MobEffect> CD_TAKABA_2 = REGISTRY.register("cd_takaba_2", () -> new CdTAKABA2MobEffect());
	public static final RegistryObject<MobEffect> HEIAN = REGISTRY.register("heian", () -> new HeianMobEffect());
	public static final RegistryObject<MobEffect> RCT_CUT = REGISTRY.register("rct_cut", () -> new RCTCutMobEffect());
	public static final RegistryObject<MobEffect> COOLDOWN_TOJI = REGISTRY.register("cooldown_toji", () -> new CooldownTojiMobEffect());
	public static final RegistryObject<MobEffect> GOJO_AWAKENING = REGISTRY.register("gojo_awakening", () -> new GojoAwakeningMobEffect());
	public static final RegistryObject<MobEffect> JOGO_FLAME = REGISTRY.register("jogo_flame", () -> new JogoFlameMobEffect());
	public static final RegistryObject<MobEffect> VOW_FRIEND = REGISTRY.register("vow_friend", () -> new VowFriendMobEffect());
	public static final RegistryObject<MobEffect> COOLDOWN_ITADORI = REGISTRY.register("cooldown_itadori", () -> new CooldownItadoriMobEffect());
	public static final RegistryObject<MobEffect> SOKA_MONA = REGISTRY.register("soka_mona", () -> new SokaMonaMobEffect());
	public static final RegistryObject<MobEffect> INFINITY = REGISTRY.register("infinity", () -> new InfinityMobEffect());
	public static final RegistryObject<MobEffect> MANIFESTATION = REGISTRY.register("manifestation", () -> new ManifestationMobEffect());
	public static final RegistryObject<MobEffect> HIDING = REGISTRY.register("hiding", () -> new HidingMobEffect());
	public static final RegistryObject<MobEffect> ONE_HUNDRED_AND_TWENTY = REGISTRY.register("one_hundred_and_twenty", () -> new OneHundredAndTwentyMobEffect());
	public static final RegistryObject<MobEffect> BLACK_FLASH_CUT = REGISTRY.register("black_flash_cut", () -> new BlackFlashCutMobEffect());
	public static final RegistryObject<MobEffect> BERSERK = REGISTRY.register("berserk", () -> new BerserkMobEffect());
	public static final RegistryObject<MobEffect> DOMAIN_TIME = REGISTRY.register("domain_time", () -> new DomainTimeMobEffect());
	public static final RegistryObject<MobEffect> SOROIRO = REGISTRY.register("soroiro", () -> new SoroiroMobEffect());
	public static final RegistryObject<MobEffect> ANTI_HEAL = REGISTRY.register("anti_heal", () -> new AntiHealMobEffect());
	public static final RegistryObject<MobEffect> MEDITATION_STATE = REGISTRY.register("meditation_state", () -> new MeditationStateMobEffect());
	public static final RegistryObject<MobEffect> TRAINING = REGISTRY.register("training", () -> new TrainingMobEffect());
	public static final RegistryObject<MobEffect> HOUR_CINDERELLA = REGISTRY.register("hour_cinderella", () -> new HourCinderellaMobEffect());
	public static final RegistryObject<MobEffect> ANIM = REGISTRY.register("anim", () -> new AnimMobEffect());
	public static final RegistryObject<MobEffect> ANIM_2 = REGISTRY.register("anim_2", () -> new Anim2MobEffect());
	public static final RegistryObject<MobEffect> ANIM_3 = REGISTRY.register("anim_3", () -> new Anim3MobEffect());
	public static final RegistryObject<MobEffect> ANIM_4 = REGISTRY.register("anim_4", () -> new Anim4MobEffect());
	public static final RegistryObject<MobEffect> ANIM_1 = REGISTRY.register("anim_1", () -> new Anim1MobEffect());
	public static final RegistryObject<MobEffect> TESTING = REGISTRY.register("testing", () -> new TestingMobEffect());
}
