
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jujutsucraftaddon.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.sounds.SoundEvent;
import net.minecraft.resources.ResourceLocation;

import net.mcreator.jujutsucraftaddon.JujutsucraftaddonMod;

public class JujutsucraftaddonModSounds {
	public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, JujutsucraftaddonMod.MODID);
	public static final RegistryObject<SoundEvent> BULLET = REGISTRY.register("bullet", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "bullet")));
	public static final RegistryObject<SoundEvent> SWORDSWEEEP = REGISTRY.register("swordsweeep", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swordsweeep")));
	public static final RegistryObject<SoundEvent> STRONG = REGISTRY.register("strong", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "strong")));
	public static final RegistryObject<SoundEvent> CURSEDSPEECH = REGISTRY.register("cursedspeech", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "cursedspeech")));
	public static final RegistryObject<SoundEvent> SOKAMONA = REGISTRY.register("sokamona", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sokamona")));
	public static final RegistryObject<SoundEvent> GOJO = REGISTRY.register("gojo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "gojo")));
	public static final RegistryObject<SoundEvent> MURASAKII = REGISTRY.register("murasakii", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "murasakii")));
	public static final RegistryObject<SoundEvent> MAHORAGALERO = REGISTRY.register("mahoragalero", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "mahoragalero")));
	public static final RegistryObject<SoundEvent> SATORUGOJO = REGISTRY.register("satorugojo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "satorugojo")));
	public static final RegistryObject<SoundEvent> PUNCH = REGISTRY.register("punch", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "punch")));
	public static final RegistryObject<SoundEvent> DASH = REGISTRY.register("dash", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "dash")));
	public static final RegistryObject<SoundEvent> SWORD = REGISTRY.register("sword", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sword")));
	public static final RegistryObject<SoundEvent> SHOKOVOICE2 = REGISTRY.register("shokovoice2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "shokovoice2")));
	public static final RegistryObject<SoundEvent> KUSAKABE = REGISTRY.register("kusakabe", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kusakabe")));
	public static final RegistryObject<SoundEvent> FURUBEYURAYURA = REGISTRY.register("furubeyurayura", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "furubeyurayura")));
	public static final RegistryObject<SoundEvent> JIHEI = REGISTRY.register("jihei", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "jihei")));
	public static final RegistryObject<SoundEvent> FUKUMAMIZUSHI = REGISTRY.register("fukumamizushi", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "fukumamizushi")));
	public static final RegistryObject<SoundEvent> GAK = REGISTRY.register("gak", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "gak")));
	public static final RegistryObject<SoundEvent> MURYOKUSHO = REGISTRY.register("muryokusho", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "muryokusho")));
	public static final RegistryObject<SoundEvent> KANGO = REGISTRY.register("kango", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kango")));
	public static final RegistryObject<SoundEvent> SWORDBLOCK = REGISTRY.register("swordblock", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swordblock")));
	public static final RegistryObject<SoundEvent> AKA2 = REGISTRY.register("aka2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "aka2")));
	public static final RegistryObject<SoundEvent> KARATE = REGISTRY.register("karate", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "karate")));
	public static final RegistryObject<SoundEvent> PUNCH2 = REGISTRY.register("punch2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "punch2")));
	public static final RegistryObject<SoundEvent> KOKUSEN = REGISTRY.register("kokusen", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kokusen")));
	public static final RegistryObject<SoundEvent> TUCADONCA = REGISTRY.register("tucadonca", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "tucadonca")));
	public static final RegistryObject<SoundEvent> SUKUNAVSMAHO = REGISTRY.register("sukunavsmaho", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavsmaho")));
	public static final RegistryObject<SoundEvent> SUKUNAVSJOGO = REGISTRY.register("sukunavsjogo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavsjogo")));
	public static final RegistryObject<SoundEvent> TOJIVSDAGONVSYUJIVSMAHITO = REGISTRY.register("tojivsdagonvsyujivsmahito", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "tojivsdagonvsyujivsmahito")));
	public static final RegistryObject<SoundEvent> GOJOVSTOJI = REGISTRY.register("gojovstoji", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "gojovstoji")));
	public static final RegistryObject<SoundEvent> YUTAVSGETO = REGISTRY.register("yutavsgeto", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "yutavsgeto")));
	public static final RegistryObject<SoundEvent> GETOVSTOJI = REGISTRY.register("getovstoji", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "getovstoji")));
	public static final RegistryObject<SoundEvent> NANAMI = REGISTRY.register("nanami", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "nanami")));
	public static final RegistryObject<SoundEvent> OVERTIME = REGISTRY.register("overtime", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "overtime")));
	public static final RegistryObject<SoundEvent> PURPLEXPLODE = REGISTRY.register("purplexplode", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "purplexplode")));
	public static final RegistryObject<SoundEvent> TAUN = REGISTRY.register("taun", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "taun")));
	public static final RegistryObject<SoundEvent> LAUGHSUKUNA = REGISTRY.register("laughsukuna", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "laughsukuna")));
	public static final RegistryObject<SoundEvent> YOAIMO = REGISTRY.register("yoaimo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "yoaimo")));
	public static final RegistryObject<SoundEvent> KURUSOGOJO = REGISTRY.register("kurusogojo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kurusogojo")));
	public static final RegistryObject<SoundEvent> GOJODEATH = REGISTRY.register("gojodeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "gojodeath")));
	public static final RegistryObject<SoundEvent> GABARE = REGISTRY.register("gabare", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "gabare")));
	public static final RegistryObject<SoundEvent> HIT = REGISTRY.register("hit", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hit")));
	public static final RegistryObject<SoundEvent> HIT2 = REGISTRY.register("hit2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hit2")));
	public static final RegistryObject<SoundEvent> HIT3 = REGISTRY.register("hit3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hit3")));
	public static final RegistryObject<SoundEvent> HITBLADE1 = REGISTRY.register("hitblade1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hitblade1")));
	public static final RegistryObject<SoundEvent> HITBLADE2 = REGISTRY.register("hitblade2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hitblade2")));
	public static final RegistryObject<SoundEvent> HITBLADE3 = REGISTRY.register("hitblade3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "hitblade3")));
	public static final RegistryObject<SoundEvent> DOMAINBREAKER = REGISTRY.register("domainbreaker", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "domainbreaker")));
	public static final RegistryObject<SoundEvent> MAXIMUMBLU = REGISTRY.register("maximumblu", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "maximumblu")));
	public static final RegistryObject<SoundEvent> TOJISPEAR = REGISTRY.register("tojispear", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "tojispear")));
	public static final RegistryObject<SoundEvent> PLAYFULHIT = REGISTRY.register("playfulhit", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "playfulhit")));
	public static final RegistryObject<SoundEvent> PLAYFULHIT2 = REGISTRY.register("playfulhit2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "playfulhit2")));
	public static final RegistryObject<SoundEvent> PLAYFULHIT3 = REGISTRY.register("playfulhit3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "playfulhit3")));
	public static final RegistryObject<SoundEvent> PLAYFULHIT4 = REGISTRY.register("playfulhit4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "playfulhit4")));
	public static final RegistryObject<SoundEvent> TOJICHAINS = REGISTRY.register("tojichains", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "tojichains")));
	public static final RegistryObject<SoundEvent> ITADORIVSMAHITO = REGISTRY.register("itadorivsmahito", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "itadorivsmahito")));
	public static final RegistryObject<SoundEvent> NANAMITHEME = REGISTRY.register("nanamitheme", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "nanamitheme")));
	public static final RegistryObject<SoundEvent> CHOSOVSITADORI = REGISTRY.register("chosovsitadori", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "chosovsitadori")));
	public static final RegistryObject<SoundEvent> METEOR = REGISTRY.register("meteor", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "meteor")));
	public static final RegistryObject<SoundEvent> CHOSOVSYUUUJI = REGISTRY.register("chosovsyuuuji", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "chosovsyuuuji")));
	public static final RegistryObject<SoundEvent> ISOHSOUND = REGISTRY.register("isohsound", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "isohsound")));
	public static final RegistryObject<SoundEvent> BATTO = REGISTRY.register("batto", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "batto")));
	public static final RegistryObject<SoundEvent> CLAP = REGISTRY.register("clap", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "clap")));
	public static final RegistryObject<SoundEvent> JUDAS = REGISTRY.register("judas", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "judas")));
	public static final RegistryObject<SoundEvent> OKKOTSUDOMAINVC = REGISTRY.register("okkotsudomainvc", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "okkotsudomainvc")));
	public static final RegistryObject<SoundEvent> PURELOVE = REGISTRY.register("purelove", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "purelove")));
	public static final RegistryObject<SoundEvent> RIKASUMMON = REGISTRY.register("rikasummon", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "rikasummon")));
	public static final RegistryObject<SoundEvent> KOKUSENMAHITO = REGISTRY.register("kokusenmahito", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kokusenmahito")));
	public static final RegistryObject<SoundEvent> KOKUSENTODO = REGISTRY.register("kokusentodo", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kokusentodo")));
	public static final RegistryObject<SoundEvent> SENKETSU = REGISTRY.register("senketsu", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "senketsu")));
	public static final RegistryObject<SoundEvent> PIERCINGBLOOD = REGISTRY.register("piercingblood", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "piercingblood")));
	public static final RegistryObject<SoundEvent> TRIPPING = REGISTRY.register("tripping", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "tripping")));
	public static final RegistryObject<SoundEvent> RUSHHR = REGISTRY.register("rushhr", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "rushhr")));
	public static final RegistryObject<SoundEvent> SLASH2 = REGISTRY.register("slash2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "slash2")));
	public static final RegistryObject<SoundEvent> SWORD4 = REGISTRY.register("sword4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sword4")));
	public static final RegistryObject<SoundEvent> SWING1 = REGISTRY.register("swing1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swing1")));
	public static final RegistryObject<SoundEvent> SWING2 = REGISTRY.register("swing2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swing2")));
	public static final RegistryObject<SoundEvent> SWING3 = REGISTRY.register("swing3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swing3")));
	public static final RegistryObject<SoundEvent> SWING4 = REGISTRY.register("swing4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swing4")));
	public static final RegistryObject<SoundEvent> SWING5 = REGISTRY.register("swing5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "swing5")));
	public static final RegistryObject<SoundEvent> PUNCH5 = REGISTRY.register("punch5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "punch5")));
	public static final RegistryObject<SoundEvent> PUNCH6 = REGISTRY.register("punch6", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "punch6")));
	public static final RegistryObject<SoundEvent> BLACKFLASHTHEME = REGISTRY.register("blackflashtheme", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "blackflashtheme")));
	public static final RegistryObject<SoundEvent> STANDPROUDSUKUNA = REGISTRY.register("standproudsukuna", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "standproudsukuna")));
	public static final RegistryObject<SoundEvent> MEDITATIONSONG = REGISTRY.register("meditationsong", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "meditationsong")));
	public static final RegistryObject<SoundEvent> CINDERELLA = REGISTRY.register("cinderella", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "cinderella")));
	public static final RegistryObject<SoundEvent> VIBRASLAP = REGISTRY.register("vibraslap", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "vibraslap")));
	public static final RegistryObject<SoundEvent> WUKONGTHEME = REGISTRY.register("wukongtheme", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wukongtheme")));
	public static final RegistryObject<SoundEvent> WUKONGULT = REGISTRY.register("wukongult", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wukongult")));
	public static final RegistryObject<SoundEvent> WU1 = REGISTRY.register("wu1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu1")));
	public static final RegistryObject<SoundEvent> WU2 = REGISTRY.register("wu2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu2")));
	public static final RegistryObject<SoundEvent> WU3 = REGISTRY.register("wu3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu3")));
	public static final RegistryObject<SoundEvent> WU4 = REGISTRY.register("wu4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu4")));
	public static final RegistryObject<SoundEvent> WU6 = REGISTRY.register("wu6", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu6")));
	public static final RegistryObject<SoundEvent> WU7 = REGISTRY.register("wu7", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu7")));
	public static final RegistryObject<SoundEvent> WU8 = REGISTRY.register("wu8", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu8")));
	public static final RegistryObject<SoundEvent> WU9 = REGISTRY.register("wu9", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu9")));
	public static final RegistryObject<SoundEvent> WU10 = REGISTRY.register("wu10", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "wu10")));
	public static final RegistryObject<SoundEvent> KYOKA = REGISTRY.register("kyoka", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kyoka")));
	public static final RegistryObject<SoundEvent> NOZARASHI = REGISTRY.register("nozarashi", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "nozarashi")));
	public static final RegistryObject<SoundEvent> NOZARASHITRUE = REGISTRY.register("nozarashitrue", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "nozarashitrue")));
	public static final RegistryObject<SoundEvent> YUJIDOMAIN = REGISTRY.register("yujidomain", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "yujidomain")));
	public static final RegistryObject<SoundEvent> SUKUNAHEART = REGISTRY.register("sukunaheart", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunaheart")));
	public static final RegistryObject<SoundEvent> MUSIC1 = REGISTRY.register("music1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music1")));
	public static final RegistryObject<SoundEvent> MUSIC2 = REGISTRY.register("music2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music2")));
	public static final RegistryObject<SoundEvent> MUSIC3 = REGISTRY.register("music3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music3")));
	public static final RegistryObject<SoundEvent> MUSIC4 = REGISTRY.register("music4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music4")));
	public static final RegistryObject<SoundEvent> SUKUNAVC1 = REGISTRY.register("sukunavc1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavc1")));
	public static final RegistryObject<SoundEvent> SUKUNAVC2 = REGISTRY.register("sukunavc2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavc2")));
	public static final RegistryObject<SoundEvent> SUKUNAVC3 = REGISTRY.register("sukunavc3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavc3")));
	public static final RegistryObject<SoundEvent> SUKUNAVC4 = REGISTRY.register("sukunavc4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavc4")));
	public static final RegistryObject<SoundEvent> SUKUNAVC5 = REGISTRY.register("sukunavc5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "sukunavc5")));
	public static final RegistryObject<SoundEvent> MUSIC5 = REGISTRY.register("music5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music5")));
	public static final RegistryObject<SoundEvent> MUSIC6 = REGISTRY.register("music6", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music6")));
	public static final RegistryObject<SoundEvent> MUSIC7 = REGISTRY.register("music7", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music7")));
	public static final RegistryObject<SoundEvent> MUSIC8 = REGISTRY.register("music8", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music8")));
	public static final RegistryObject<SoundEvent> MUSIC9 = REGISTRY.register("music9", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music9")));
	public static final RegistryObject<SoundEvent> MUSIC10 = REGISTRY.register("music10", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "music10")));
	public static final RegistryObject<SoundEvent> KAI = REGISTRY.register("kai", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "kai")));
	public static final RegistryObject<SoundEvent> DISMANTLE = REGISTRY.register("dismantle", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("jujutsucraftaddon", "dismantle")));
}
